services:
  backend:
    container_name: backend_docker_instance
    restart: on-failure
    build: .
    ports:
      - 5000:5000
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
